date: "2022-02-23"
title: "前端性能指标与优化方法"
tags: ["fe"]
abstract: "本文简述前端性能指标与常用的优化方法"
requirements: []
references:
  [
    ["web.dev", "https://web.dev/"],
    [
      "User-centric performance metrics",
      "https://web.dev/user-centric-performance-metrics/#in-the-lab",
    ],
  ]
