date: "2021-05-18"
title: "React 状态更新原理简析"
tags: ["fe", "react", "source"]
abstract: "React 状态更新原理简析。"
requirements: ["使用过 React", "了解 React Fiber 结构", "熟悉数据结构 - 树"]
series: "react-analysis"
references:
  [
    [
      "React 技术揭秘 - 第六章 状态更新",
      "https://react.iamkasong.com/state/prepare.html",
    ],
    [
      "10.scheduler&lane模型(来看看react是暂停、继续和插队的)",
      "https://xiaochen1024.com/article_item/600acd54245877002ed5df04",
    ],
  ]
