date: "2021-06-14"
title: "CSS Animation 学习笔记"
tags: ["fe", "css"]
abstract: "本文为笔者的 CSS transition, animation 与 JS animation 等的学习笔记，主要以复现其他人 demo 的形式。"
codeDemo:
  root: "./demos"
  codes:
    - key: "file-tabs"
      path: "file-tabs"
      entry: "index.js"
      files: ["index.html", "index.js", "index.css"]
      template: "vanilla"
    - key: "loader-rect-flip"
      path: "loader-rect-flip"
      entry: "index.js"
      files: ["index.html", "index.js", "index.css"]
      template: "vanilla"
    - key: "loaderball"
      path: "loaderball"
      entry: "index.js"
      files: ["index.html", "index.js", "index.css"]
      template: "vanilla"
    - key: "toggle-switch"
      path: "toggle-switch"
      entry: "index.js"
      files: ["index.html", "index.js", "index.css"]
      template: "vanilla"
    - key: "typewriter"
      path: "typewriter"
      entry: "index.js"
      files: ["index.html", "index.js", "index.scss"]
      template: "vanilla"
