date: "2022-04-03"
title: "从库学 Rust - tower"
tags: ["rust"]
abstract: "本文会介绍 tower 的核心、部分工具与特性，并会手动实现一部分工具与特性。"
requirements: []
series: "learn-rust-by-lib"
references:
  [
    ["tower - Github", "https://github.com/tower-rs/tower"],
    [
      "Inventing the Service trait",
      "https://tokio.rs/blog/2021-05-14-inventing-the-service-trait",
    ],
  ]
