import Head from "next/head";
import Image from "next/image";
import { GetStaticProps } from "next";
import { getPosts } from "@/data/posts.data";
import Link from "next/link";
import { getPostHref, PostMeta, TAGS } from "@/core/post.core";
import { AppBar, AppBarMenuMask } from "@/widgets/appbar";
import { fmtDate } from "@/utils/common";
import styles from "./materials.module.scss";
import { FullscreenScrollable, Layout, CommonLayout } from "@/widgets/layout";
import {
  MaterialConfig,
  MaterialItem,
  recommendMaterials,
  selfMaterials,
} from "@/core/material.core";

interface Props {
  metas: PostMeta[];
}

export const getStaticProps: GetStaticProps<Props> = async (context) => {
  const metas = await getPosts();
  return {
    props: {
      metas,
    }, // will be passed to the page component as props
  };
};

function MaterialItemCard({ item }: { item: MaterialItem }) {
  return (
    <a
      className={styles.item}
      href={item.link}
      target="_blank"
      rel="noreferrer"
    >
      <div className={styles.title}>{item.title}</div>
      <div className={styles.desc}>{item.description}</div>
    </a>
  );
}

function MaterialItems({ config }: { config: MaterialConfig }) {
  return (
    <>
      {config.map((conf, idx) => (
        <div key={idx}>
          <div className={styles.section}>{conf.section}</div>
          <div className={styles.itemsContainer}>
            {conf.items.map((item, idx) => (
              <MaterialItemCard key={idx} item={item} />
            ))}
          </div>
        </div>
      ))}
    </>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>GrayWood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonLayout className={styles.materials}>
        <h2 className={styles.title}>Recommend Materials</h2>
        <h3 className={styles.subTitle}>
          这里收集了一些笔者认为不错的系统化的资料
        </h3>
        <MaterialItems config={recommendMaterials} />
        <h2 className={styles.title}>My Materials</h2>
        <h3 className={styles.subTitle}>这里是笔者的一些项目</h3>
        <MaterialItems config={selfMaterials} />
      </CommonLayout>
    </>
  );
}
