date: "2024-08-25"
title: "FreeType 灰度光栅化器的实现"
tags: ["render"]
abstract: "本文以笔者的理解阐述 freetype 灰度光栅化器 ftgrays 代码的核心实现"
requirements: []
references: [["freetype", "https://gitlab.freedesktop.org/freetype/freetype"]]
