date: "2021-11-27"
title: "常用通信协议 - DNS"
tags: ["fe"]
abstract: ""
requirements: []
series: "common-communications-protocol"
references:
  [
    ["DNS 原理入门", "https://www.ruanyifeng.com/blog/2016/06/dns.html"],
    [
      "What is DNS? | How DNS works",
      "https://www.cloudflare.com/learning/dns/what-is-dns/",
    ],
    [
      "DNS: Types of DNS Records, DNS Servers and DNS Query Types",
      "https://ns1.com/resources/dns-types-records-servers-and-queries",
    ],
    ["云解析 DNS", "https://help.aliyun.com/document_detail/102237.html"],
  ]
